Feat/employee profile
Team1-TeliaProject/team1_FrontEnd pull request #35
Opened 2021-04-03 17:54 UTC by Alabbey2

![employee-profile-screenshot](https://user-images.githubusercontent.com/47299377/113487063-8d48fd00-94be-11eb-8378-065461af8a32.PNG)

2021-04-04 18:38 UTC, shresthapr submitted a review, later dismissed

2021-04-05 09:05 UTC, Chiranjibichapagain commented on client/src/Components/EmployeeProfile/index.js
> +import Header from '../Header/Header'
Here you are building 2 components together. When you are working on the EmployeeeProfile component just work on that. You are building heard as well here which 1 is not a good practice and 2. there is no header component in our backlog, we have a navigation component which i am doing. so you don't have to worry about how the header will look like. just do employee profile here. :)

2021-04-05 09:18 UTC, Chiranjibichapagain requested changes

2021-04-05 09:18 UTC, Chiranjibichapagain commented on client/src/Components/EmployeeProfile/index.js
> +
exclude header from this component

2021-04-05 09:18 UTC, Chiranjibichapagain commented on client/src/Components/EmployeeProfile/index.js
> +                        <img className="employee-profile__image__big" src="/image/user.png" />
the className convention when you use modifier is : "employee-profile__image employee-profile__image--big"  and  "employee-profile__image employee-profile__image--small"

2021-04-05 09:18 UTC, Chiranjibichapagain commented on client/src/Components/EmployeeProfile/index.js
> +                       <Button text="Edit Profile" modifier="md" />
Every data you passed in should be dynamic and passed via props. You are hard coding the data here make dummy data and pass those data via props to the component from App.js to test the component.  Eg: "h2 Talent name h2 " not like this. get the talent name from props and use that name like: " h2 {talentName} h2 "

2021-04-05 09:18 UTC, Chiranjibichapagain commented on client/src/Components/EmployeeProfile/EmployeeProfile.scss
> +        .logo__main {
We need to make our css style consistent. Please check the button component and try to align your css writing style with it. You can also check the better way of using modifiers there.

2021-04-05 09:18 UTC, Chiranjibichapagain commented on client/src/Components/EmployeeProfile/index.js
> +                        <img className="employee-profile__image__big" src="/image/user.png" />
In fact, you don't need a modifier at all for this component. as navigation component will take care of the small profile image. you just need to create the image for the talent profile. And try with the real image not SVG.

2021-04-05 21:04 UTC, Alabbey2 commented
![new_employee-profile-update](https://user-images.githubusercontent.com/47299377/113627054-9a571f00-966b-11eb-874c-ec14ec8136c2.PNG)

2021-04-07 09:02 UTC, Chiranjibichapagain requested changes

2021-04-07 09:02 UTC, Chiranjibichapagain commented on client/src/Components/EmployeeProfile/index.js
> +                    </div>
Please review the SCSS reviewing style

2021-04-07 11:33 UTC, Alabbey2 commented
![style1](https://user-images.githubusercontent.com/47299377/113859997-338e4e80-97ae-11eb-8be8-a3ac0be20018.PNG)

2021-04-07 11:34 UTC, Alabbey2 commented
update

2021-04-07 11:42 UTC, Chiranjibichapagain submitted a review, later dismissed

2021-04-08 05:58 UTC, merged