[feat/profileDrop..] profile component + app.scss responsiveness modi…
Team1-TeliaProject/team1_FrontEnd pull request #39
Opened 2021-04-05 16:45 UTC by shresthapr

closes #19 

<img width="365" alt="Screen Shot 2021-04-05 at 7 41 00 PM" src="https://user-images.githubusercontent.com/69511034/113599513-62d67b80-9647-11eb-958d-dd05af18d9d1.png">

profile component

2021-04-07 08:31 UTC, Chiranjibichapagain commented on client/src/Components/ProfileDropdown/index.js
> +      <section className="profDropDn">
Not very important but maybe className="dropdown" is enough if you wish to make it more descriptive the className for scss are written in this format: prof-drop-dn not profDropDn

2021-04-07 08:36 UTC, Chiranjibichapagain commented on client/src/Components/ProfileDropdown/index.js
> +      </section>
"profDropDn__edit profDropDn__edit__text"  i didn't understand this one. Here you have two elements under profDropDn__edit. as we cannot go further than 1 step the best way to name class for p and the icon is profDropDn__text and profDropDn__icon. 

Also please give classNames to the icons and give styling from the SCSS. Maybe we cannot give color from the SCSS file. not sure try. if it doesn't work then give color with inline styles.

2021-04-07 11:55 UTC, Chiranjibichapagain requested changes
please review the classNames

2021-04-08 06:19 UTC, Chiranjibichapagain approved these changes, later dismissed
:+1:

2021-04-08 06:53 UTC, SaharPerveen submitted a review, later dismissed

2021-04-08 06:55 UTC, Alabbey2 approved these changes, later dismissed
all good

2021-04-08 07:34 UTC, merged